import {Dimensions, StyleSheet} from 'react-native';
import {
  getFontSize,
  scaledHeightValue,
  scaledValue,
} from '../../../utils/design.utils';
import {colors} from '../../../../assets/colors';
import fonts from '../../../utils/fonts';
const deviceW = Dimensions.get('window').width;
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerLeftIconStyle: {
    tintColor: 'white',
    height: scaledValue(40),
    width: scaledValue(40),
  },
  imgbg: {
    resizeMode: 'cover',
    width: '100%',
    height: '100%',
    // marginBottom: scaledValue(-100),
    // bottom: 60,
  },
  gradient: {
    position: 'absolute',
    height: '55%',
    width: '100%',
    bottom: 0,
    alignItems: 'center',
    overflow: 'hidden',
  },

  button: {
    borderRadius: 40,
    height: scaledHeightValue(37),
    width: scaledValue(156),
    backgroundColor: colors.darkShadeOfPurple,
    borderWidth: scaledValue(2.5),
    borderColor: colors.themeColor,
    marginBottom: scaledValue(8),
    alignSelf: 'center',
  },
  leftArrowStyle: insets => ({
    tintColor: 'white',
    height: scaledValue(40),
    width: scaledValue(40),
  }),
  nameText: {
    textAlign: 'center',
    lineHeight: scaledValue(39.6),
    letterSpacing: scaledValue(33 * -0.03),
    fontSize: scaledValue(33),
    color: colors.offWhite,
  },
  placeText: {
    textAlign: 'center',
    lineHeight: scaledHeightValue(18.2),
    fontSize: getFontSize(14),
    color: '#FFF4EC',
    letterSpacing: scaledValue(4),
    opacity: 0.7,
  },
  flatlistMain: {
    borderWidth: 1,
    borderRadius: scaledValue(32),
    backgroundColor: colors.offWhite,
    borderColor: '#4B164C33',
    marginLeft: scaledValue(4),
    height: scaledValue(35),
    alignItems: 'center',
    justifyContent: 'center',
  },
  skillText: {
    fontSize: getFontSize(16),
    color: colors.darkPurple,
    letterSpacing: scaledValue(16 * -0.03),
    fontFamily: fonts.SUSE_REGULAR,
    maxWidth: scaledValue(115),
  },
  swipeImage: {
    resizeMode: 'contain',
    height: scaledHeightValue(20),
    width: scaledValue(20),
  },
  swipeView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scaledHeightValue(24),
    gap: scaledValue(4),
    zIndex: 100,
  },
  swipingText: {
    color: colors.peachy,
    fontSize: getFontSize(14),
    letterSpacing: scaledValue(14 * -0.02),
    lineHeight: scaledValue(18.2),
    marginLeft: scaledValue(2),
  },
  roundedRect: insets => ({
    height: scaledValue(72),
    width: scaledValue(248),
    borderRadius: scaledValue(40),
    backgroundColor: colors.offWhite,
    alignSelf: 'center',
    // marginBottom: insets.bottom + scaledHeightValue(4),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
  }),
  rectView: {
    height: scaledHeightValue(64),
    width: scaledValue(204),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rejectView: {
    height: scaledValue(40),
    width: scaledValue(40),
    borderRadius: scaledValue(40),
    backgroundColor: colors.softRed,
    alignItems: 'center',
    justifyContent: 'center',
    // opacity: 0.3,
  },
  acceptedView: {
    height: scaledValue(60),
    width: scaledValue(60),
    borderRadius: scaledValue(40),
    backgroundColor: colors.themeColor,
    alignItems: 'center',
    resizeMode: 'contain',
    justifyContent: 'center',
  },
  saveView: {
    height: scaledValue(40),
    width: scaledValue(40),
    borderRadius: scaledValue(20),
    backgroundColor: colors.peachy,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rejectImage: {
    height: scaledValue(20),
    width: scaledValue(20),
    resizeMode: 'contain',
  },
  acceptedImage: {
    height: scaledValue(30),
    width: scaledValue(30),
    tintColor: colors.white,
  },
  saveImage: {
    height: scaledValue(20),
    width: scaledValue(20),
    resizeMode: 'contain',
  },
  buttonText: {
    fontSize: scaledValue(19),
    fontFamily: fonts.SUSE_MEDIUM,
    letterSpacing: scaledValue(19 * -0.03),
    elevation: 100,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.5,
    shadowRadius: scaledValue(8),
    borderRadius: scaledValue(8),
  },
  rbsheetHeader: {
    fontSize: scaledValue(19),
    letterSpacing: scaledValue(19 * -0.03),
    marginTop: scaledValue(12),
  },
  rbsheetContent: {
    fontSize: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.02),
    lineHeight: scaledValue(20.8),
    color: colors.darkPurpleBlack,
    marginTop: scaledValue(8),
  },
  rbsheetContentView: {
    width: deviceW - 40,
  },

  careerCardView: {
    marginTop: scaledHeightValue(10),
    paddingHorizontal: scaledValue(25),
    marginBottom: scaledHeightValue(18),
    width: Dimensions.get('screen').width,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    rowGap: scaledValue(8),
    columnGap: scaledValue(4),
  },
  careerListView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: scaledValue(6),
    justifyContent: 'center',
    rowGap: scaledValue(8),
  },
  careerCardTouchable: {
    height: scaledHeightValue(35),
    borderRadius: scaledValue(24),
    justifyContent: 'center',
    backgroundColor: colors.offWhite,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scaledValue(12),
    gap: scaledValue(5),
  },
  leftArrowView: insets => ({
    paddingLeft: scaledValue(24.06),
    position: 'absolute',
    top: insets.top + scaledValue(13),
    zIndex: 10,
    elevation: 100,
    shadowColor: '#000000',
    shadowOffset: {width: -5, height: 10},
    shadowOpacity: 0.7,
    shadowRadius: scaledValue(10),
    borderRadius: scaledValue(8),
  }),
  renderContainer: {
    width: Dimensions.get('window').width,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  userImg: {
    resizeMode: 'cover',
    width: '100%',
    height: '100%',
  },
  container: {flex: 1, padding: 20, backgroundColor: '#fff'},
  itemContainer: {
    padding: 15,
    backgroundColor: '#ddd',
    marginVertical: 5,
    borderRadius: 5,
  },
  itemText: {fontSize: 16},

  tutorialContainer: {
    width,
    height,
    // backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#3E3E3EB2',
  },
  tutorialPage: {
    width,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  tutorialTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 10,
  },
  tutorialDescription: {
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
    marginBottom: 20,
  },

  dot: {
    backgroundColor: colors.offWhite,
    width: scaledValue(10),
    height: scaledValue(10),
    borderRadius: scaledValue(10),
    marginHorizontal: scaledValue(7),
    opacity: 0.5,
  },
  activeDot: {
    backgroundColor: colors.offWhite,
    width: scaledValue(22.86),
    height: scaledValue(10),
    borderRadius: scaledValue(8),
  },

  nextButton: {
    position: 'absolute',
    bottom: 50,
    backgroundColor: 'blue',
    padding: 12,
    borderRadius: 5,
  },
  nextButtonText: {color: 'white', fontSize: 16, fontWeight: 'bold'},

  skipButton: {position: 'absolute', top: 40, right: 20},
  skipButtonText: {color: 'white', fontSize: 16},
  screen: {
    width,
    height,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
});
