import {Dimensions, StyleSheet} from 'react-native';
import fonts from '../../../../utils/fonts';
import {colors} from '../../../../../assets/colors';
import {
  getFontSize,
  scaledHeightValue,
  scaledValue,
} from '../../../../utils/design.utils';
const deviceW = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // alignItems: 'center',
    backgroundColor: colors.offWhite,
  },
  headerText1: {
    color: colors.black,
    fontFamily: fonts.SUSE_SEMIBOLD,
    fontSize: getFontSize(16),
    lineHeight: scaledHeightValue(19.2),
    letterSpacing: scaledValue(16 * -0.03),
  },
  headerText2: {
    color: colors.inputPlaceholder,
  },
  basicInfoText: {
    marginTop: scaledHeightValue(15),
    textAlign: 'center',
    fontSize: scaledHeightValue(23),
    fontFamily: fonts.SUSE_MEDIUM,
    color: colors.themeColor,
    letterSpacing: scaledValue(23 * -0.02),
  },
  uploadText: {
    textAlign: 'center',
    fontSize: getFontSize(19),
    fontFamily: fonts.SUSE_MEDIUM,
    color: colors.themeColor,
    letterSpacing: scaledValue(19 * -0.03),
    lineHeight: scaledHeightValue(22.8),
    marginBottom: scaledHeightValue(42),
  },
  contentText: {
    textAlign: 'center',
    marginTop: scaledHeightValue(16),
    fontFamily: fonts.BE_VIETNAM_REGULAR,
    lineHeight: scaledHeightValue(18.2),
    letterSpacing: scaledValue(14 * -0.02),
    fontSize: getFontSize(14),
    color: colors.Gray,
    marginBottom: scaledHeightValue(31),
  },
  gradientStyle: {
    height: scaledHeightValue(48),
    width: deviceW - 40,
    // marginBottom: scaledHeightValue(40),
    // marginTop: scaledHeightValue(49),
    alignSelf: 'center',
  },
  textStyle: {
    fontSize: getFontSize(19),
    fontFamily: fonts.SUSE_MEDIUM,
    lineHeight: scaledHeightValue(22.8),
    letterSpacing: 19 * -0.03,
    paddingLeft: scaledValue(4),
  },
  verifiedImage: {
    resizeMode: 'contain',
    height: scaledHeightValue(17.5),
    width: scaledValue(17.5),
  },
  circularBg: {
    height: scaledHeightValue(100),
    width: scaledHeightValue(100),
    resizeMode: 'contain',
    marginTop: scaledHeightValue(56),
    alignSelf: 'center',
    marginBottom: scaledHeightValue(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientFace: {
    height: scaledHeightValue(52.5),
    width: scaledHeightValue(52.5),
    opacity: scaledValue(0.5),
  },
  cameraBg: {
    height: scaledHeightValue(32),
    width: scaledHeightValue(32),
    borderRadius: scaledValue(16),
    backgroundColor: colors.offWhite,
    position: 'absolute',
    bottom: 0,
    right: scaledValue(-5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientCamera: {
    height: scaledHeightValue(13.14),
    width: scaledValue(14.86),
  },
  inputField: {
    height: scaledHeightValue(122),
    borderRadius: scaledValue(12),
    borderWidth: scaledValue(1),
    borderColor: colors.themeColor,
    marginBottom: scaledHeightValue(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordsView: {
    height: scaledHeightValue(16),
    marginBottom: scaledHeightValue(32),
    alignItems: 'flex-end',
  },
  wordsText: {
    fontSize: scaledValue(12),
    lineHeight: scaledHeightValue(15.6),
    color: colors.Gray,
  },
  bioText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16),
    letterSpacing: scaledValue(14 * -0.03),
    color: colors.themeColor,
  },
  bioBg: {
    height: scaledHeightValue(16),
    width: scaledValue(68),
    paddingHorizontal: scaledValue(4),
    backgroundColor: colors.offWhite,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: scaledHeightValue(-8),

    marginLeft: scaledValue(28),
  },
  textInput: {
    borderRadius: scaledValue(12),
    borderColor: colors.themeColor,
    height: scaledHeightValue(130),
    width: deviceW - 40,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(18.2),
    letterSpacing: scaledValue(18 * -0.02),
    textAlignVertical: 'top',
  },
  preferenceText: {
    fontSize: getFontSize(19),
    lineHeight: scaledHeightValue(22.8),
    letterSpacing: scaledValue(19 * -0.03),
    color: colors.charcoal,
  },
  textView: {
    gap: 12,
  },
  mentorText: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  preferenceTextView: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginBottom: scaledHeightValue(12),
    alignSelf: 'center',
    width: '65%',
    justifyContent: 'center',
  },
  firstText: {
    fontSize: getFontSize(19),
    fontFamily: fonts.SUSE_MEDIUM,
    lineHeight: scaledHeightValue(22.8),
    letterSpacing: scaledValue(19 * -0.03),
    paddingRight: scaledValue(4),
    color: colors.charcoal,
  },
  secondText: {
    fontSize: getFontSize(19),
    fontFamily: fonts.SUSE_MEDIUM,
    lineHeight: scaledHeightValue(22.8),
    letterSpacing: scaledValue(19 * -0.03),
    paddingRight: scaledValue(4),
  },
  arrowStyle: {
    height: scaledHeightValue(20),
    width: scaledValue(20),
    resizeMode: 'contain',
  },
  wordCountText: {
    marginBottom: scaledHeightValue(52),
    alignItems: 'flex-end',
    right: scaledValue(20),
    marginTop: scaledValue(4),
  },
  countingText: {
    color: colors.inputPlaceholder,
    fontSize: getFontSize(12),
  },
  preferenceHeader: {
    fontSize: getFontSize(19),
    letterSpacing: scaledValue(19 * -0.03),
    lineHeight: scaledHeightValue(22.8),
    marginBottom: scaledHeightValue(12),
  },
});
